//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_manufacturers
    {
        public C_manufacturers()
        {
            this.C_products = new HashSet<C_products>();
        }
    
        public int ID_manufacturer { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<C_products> C_products { get; set; }
    }
}
