//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_orders
    {
        public C_orders()
        {
            this.C_order_parts = new HashSet<C_order_parts>();
        }
    
        public int ID_order { get; set; }
        public string date_ordered { get; set; }
        public string date_recieved { get; set; }
        public int PVZ_ID { get; set; }
        public Nullable<int> user_ID { get; set; }
        public string code { get; set; }
        public int status_ID { get; set; }
    
        public virtual ICollection<C_order_parts> C_order_parts { get; set; }
        public virtual C_PVZ C_PVZ { get; set; }
        public virtual C_statuses C_statuses { get; set; }
        public virtual C_users C_users { get; set; }
    }
}
