//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_order_parts
    {
        public int ID_part { get; set; }
        public string article { get; set; }
        public int count { get; set; }
        public int order_ID { get; set; }
    
        public virtual C_orders C_orders { get; set; }
        public virtual C_products C_products { get; set; }
    }
}
