//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_products
    {
        public C_products()
        {
            this.C_order_parts = new HashSet<C_order_parts>();
        }
    
        public string article { get; set; }
        public string name { get; set; }
        public double price { get; set; }
        public int provider_ID { get; set; }
        public int manufacturer_ID { get; set; }
        public int category_ID { get; set; }
        public double discount { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string image_path { get; set; }
    
        public virtual C_categories C_categories { get; set; }
        public virtual C_manufacturers C_manufacturers { get; set; }
        public virtual ICollection<C_order_parts> C_order_parts { get; set; }
        public virtual C_providers C_providers { get; set; }
    }
}
