//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_PVZ
    {
        public C_PVZ()
        {
            this.C_orders = new HashSet<C_orders>();
        }
    
        public int ID_PVZ { get; set; }
        public string info { get; set; }
    
        public virtual ICollection<C_orders> C_orders { get; set; }
    }
}
