//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_roles
    {
        public C_roles()
        {
            this.C_users = new HashSet<C_users>();
        }
    
        public int ID_role { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<C_users> C_users { get; set; }
    }
}
