//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_users
    {
        public C_users()
        {
            this.C_orders = new HashSet<C_orders>();
        }
    
        public int ID_user { get; set; }
        public int role_ID { get; set; }
        public string FIO { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<C_orders> C_orders { get; set; }
        public virtual C_roles C_roles { get; set; }
    }
}
