//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demex3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C_categories> C_categories { get; set; }
        public DbSet<C_manufacturers> C_manufacturers { get; set; }
        public DbSet<C_order_parts> C_order_parts { get; set; }
        public DbSet<C_orders> C_orders { get; set; }
        public DbSet<C_products> C_products { get; set; }
        public DbSet<C_providers> C_providers { get; set; }
        public DbSet<C_PVZ> C_PVZ { get; set; }
        public DbSet<C_roles> C_roles { get; set; }
        public DbSet<C_statuses> C_statuses { get; set; }
        public DbSet<C_users> C_users { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
